services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    networks:
      - rickrolls-api-network
    environment:
      MYSQL_DATABASE: CHANGE THIS
      MYSQL_ROOT_PASSWORD: CHANGE THIS
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: CHANGE THIS
    networks:
      - rickrolls-api-network
    restart: unless-stopped

  prod-api:
    stdin_open: true
    build: .
    image: rickrolls-api:v1
    container_name: prod-api
    hostname: CHANGE THIS VALUE IF YOU REALLY WANT TO USE THIS PROPERTY
    env_file: .env
    networks:
      - rickrolls-api-network
    volumes:
      - ./:/app
    depends_on:
      mysql:
        condition: service_started
    ports:
      - 80:5000
    expose:
      - 5000

networks:
  rickrolls-api-network:
    external: true
