version: "3.9"

services:
  rickrolls-backend:
    hostname: rickrolls-api.jesunmaailma.tk
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:5000"
    links:
      - rickrolls_db
    stdin_open: true
    tty: true

  rickrolls_db:
    container_name: rickrolls_db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/usr/share/postgresql/data
    environment:
      - POSTGRES_PASSWORD=salasana
      - POSTGRES_DB=rickrolls

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=juiceneblueyt@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=salasana

networks:
  default:
    driver: bridge
