version: "3.9"

services:
  rickrolls-backend:
    hostname: rickrolls-backend
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    restart: unless-stopped
    depends_on:
      - rickrolls_db
    env_file:
      - .env
    ports:
      - "7080:5000"
    links:
      - rickrolls_db
    stdin_open: true
    tty: true

  rickrolls_db:
    container_name: rickrolls_db
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./data:/data/db
    environment:
      - POSTGRES_PASSWORD=salasana
      - POSTGRES_DB=rickrolls
