name: "Rakenna"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kirjaudu GitHub Container Registryyn
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ../../server/
          push: true
          tags: ghcr.io/theisoj/rickrolls-backend